# Ansible
# ansible_user: root

# Kubernetes version to be installed
k8s_version: "1.21.0"

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add..
kubeadm_opts: ""
# For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'

service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.140.140.0/24"

# Network implementation('flannel', 'calico', 'canal')
network: calico

# Change this to an appropriate interface, preferably a private network.
# For example, on DigitalOcean, you would use eth1 as that is the default private network interface.
network_interface: ""

network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf

# Additional feature to install
additional_features:
  helm: true
  metallb: true
  nginx_ingress: true

# temporary directory used by additional features
tmp_dir: /tmp/kubeadm-ansible-files

# Container runtimes ('docker', 'containerd', 'crio')
container_runtime: docker

# helm helm version
helm_version: "v3.5.4"

# SELinux state to be set on k8s nodes                 
selinux_state: permissive                              

# Timezone to set on all nodes
timezone: "Asia/Baku"                                  

# calico, flannel
k8s_cni: calico  

# Add hostnames to /etc/hots file
configure_etc_host_file: true                        

# NFS configs
setup_nfs: true
folders: ["default","kafka","userprofile"]

# haproxy
haproxy_version: 2.2.14
haproxy_port: 8443

# keepalived
keepalived_virtual_ip: 172.18.184.180/32

# control plane host
control_plane_host: test-k8s-m

# root-ca directory
root_ca_directory: /tmp/rootca

# metallb

metallb_version: v0.11.0
metallb_yaml_url: "https://raw.githubusercontent.com/google/metallb/{{ metallb_version }}/manifests/metallb.yaml"
metallb_namespace_yaml_url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/metallb.yaml"
metallb_address_space: 192.168.205.200-192.168.205.210