---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: helm

- name: "Install Helm"
  block:
    - name: "Get Helm installer"
      get_url:
        url: https://azol-os-repo.simbrella.pro:9443/sre-repo/Packages/helm-{{ helm_version }}-linux-amd64.tar.gz
        dest: "{{ tmp_dir }}/helm-{{ helm_version }}-linux-amd64.tar.gz"

    - name: Extract helm-{{ helm_version }}-linux-amd64.tar.gz
      ansible.builtin.unarchive:
        src: "{{ tmp_dir }}/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: "{{ tmp_dir }}"
        remote_src: yes
  tags: helm

- name: Move Helm binary it to its desired destination
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/linux-amd64/helm"
    dest: /bin/
    mode: '700'
    remote_src: yes

- debug:
    msg: "{{ item.repo }}"
  with_items:
    - "{{ repo_list }}"    

- name: Add Helm chart repositories
  kubernetes.core.helm_repository:
    name: "{{ item.repo.name }}"
    repo_url: "{{ item.repo.url }}"
  with_items:
    - "{{ repo_list }}"
  vars:
    ansible_python_interpreter: /bin/python3

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: helm
