---
# - hosts: repo
#   gather_facts: yes
#   become: yes
#   tasks:
#     - name: "NFS setup"
#       include_role:
#         name: nfs
#       when: "setup_nfs"
#       run_once: yes
#       tags: nfs

# - hosts: kube-cluster
#   gather_facts: yes
#   become: yes
#   become_method: sudo
#   roles:
#     - { role: commons/pre-install, tags: pre-install }

# - hosts: master
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: commons/firewall-rules/master, tags: master }

# - hosts: worker
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: commons/firewall-rules/worker, tags: worker } 

# - hosts: master
#   gather_facts: yes
#   become: yes
#   tasks:
#     - name: "Keepalived setup"
#       include_role:
#         name: keepalived
#       when: master_hosts_count | int >= 3
#       tags: keepalived

# - hosts: master
#   gather_facts: yes
#   become: yes
#   tasks:
#     - name: "Haproxy setup"
#       include_role:
#         name: haproxy
#       when: master_hosts_count | int >= 3
#       tags: haproxy

# - hosts: kube-cluster
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: container-runtime, tags: container-runtime }

# - hosts: master
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: kubernetes/master, tags: master }
#     - { role: cni, tags: cni }

# - hosts: worker
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: kubernetes/worker, tags: worker }

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Nginx-Ingress role"
      include_role:
        name: nginx-ingress
      when: "additional_features.nginx_ingress"
      run_once: yes
      tags: nginx-ingress