---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Copy join command from Ansiblehost to the worker nodes
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 077
     
- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  command: sh /tmp/kubernetes_join_command
  register: join_cluster
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"
  notify:
    - Recreate kube-dns
