---
- name: Copy a root ca into place
  copy:
    src: "{{ item }}"
    dest: /etc/pki/ca-trust/source/anchors/
  with_fileglob:
    - /tmp/rootca/*

- name: Update CA Trust (Red Hat)
  command: update-ca-trust