---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Open flannel ports on the firewall
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
  with_items: "{{ flannel_udp_ports }}"
  when: k8s_cni == "flannel"

- name: Open calico UDP ports on the firewall
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
  with_items: "{{ calico_udp_ports }}"
  when: k8s_cni == "calico"

- name: Open calico TCP ports on the firewall
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items: "{{ calico_tcp_ports }}"
  when: k8s_cni == "calico"

- name: Reload firewalld
  shell: firewall-cmd --reload
