---
- name: Add kubernetes repository
  ansible.builtin.template:
    src: 'kubernetes.repo.j2'
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install kubernetes packages
  ansible.builtin.yum:
    name: 
      - kubelet-{{ k8s_version }}
      - kubeadm-{{ k8s_version }}
      - kubectl-{{ k8s_version }}
    disable_excludes: kubernetes

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
