---
- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"

- name: Add repository
  yum_repository:
    name: sre-repo
    description: local-sre-repo
    baseurl: https://azol-os-repo.simbrella.pro:9443/sre-repo/
    gpgcheck: no
    enabled: yes

- name: Yum clean cache
  command: yum clean all

- name: Update system packages
  package:
    name: "*"
    state: latest

- name: Install some packages needed to configure the nodes
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - "{{ basic_packages }}"
  
- name: Install some python packages needed to configure the ansible
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - "{{ python_packages }}"

- name: Disable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
