---

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: >
    {{ lookup('template', 'join.j2') }}  
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"
  notify:
    - Recreate kube-dns