---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Install keepalived
  include_tasks: pkg.yml
  when: master_hosts_count | int >= 3

- name: Init cluster if needed
  include_tasks: init.yml
  run_once: yes

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: Join to cluster
  include_tasks: join.yml

- name: "Copy config file"
  fetch:
    src: /etc/kubernetes/admin.conf 
    dest: "{{ lookup('env', 'HOME') }}/admin.conf"
    flat: yes
  run_once: yes
  ignore_errors: yes