---
- name: Install keepalived package
  ansible.builtin.yum:
    name: keepalived
    state: latest

- name: Create haproxy check script
  ansible.builtin.template:
    src: check_haproxy.j2
    dest: /etc/keepalived/check_haproxy.sh
    mode: '0755'

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived_config.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start and enable keepalived service
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: yes