---
# Master nodes firewall ports
k8s_master_ports:
    - 22
    - 80
    - 443
    - 6443
    - 2379-2380
    - 10250
    - 10251
    - 10252

# Worker nodes firewall ports
k8s_worker_ports:
    - 22
    - 80
    - 443
    - 10250
    - 30000-32767

# Calico CNI firewall ports
calico_udp_ports:
  - 4789
calico_tcp_ports:
  - 5473
  - 179
  - 5473

# Flannel CNI firewall ports
flannel_udp_ports:
  - 8285
  - 8472

# Default pod subnet for cri-o runtime
pod_network_cidr:
  - "10.85.0.0/16"

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon