---
metallb_version: v0.11.0
metallb_yaml_url: "https://raw.githubusercontent.com/google/metallb/{{ metallb_version }}/manifests/metallb.yaml"
metallb_namespace_yaml_url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/metallb.yaml"
metallb_address_space: 192.168.205.200-192.168.205.210
