---

- name: Add docker repository
  when: container_runtime == "docker" or container_runtime == "containerd"
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Install supported version of docker
  when: container_runtime == "docker"
  ansible.builtin.package:
    name: [docker-ce]
    state: present

- name: Configure Cri-o YUM repository
  when: container_runtime == "cri-o"
  ansible.builtin.template:
    src: crio.repo.j2
    dest: /etc/yum.repos.d/crio.repo    

