---
- name: Create other directories required
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: Set cgroup driver as systemd
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Start and enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Restart docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes